const ALCHEMY_API_KEY = process.env.ALCHEMY_API_KEY ?? "";
const ALCHEMY_GAS_MANAGER_POLICY_ID = process.env.NEXT_PUBLIC_ALCHEMY_GAS_MANAGER_POLICY_ID ?? "";
export { ALCHEMY_API_KEY, ALCHEMY_GAS_MANAGER_POLICY_ID };
