import { apiUrl, rpcUrl, rpcUrlWChain } from "./AlchemyConsts";
import {
  NEXT_PUBLIC_ALCHEMY_API_KEY,
  NEXT_PUBLIC_ALCHEMY_GAS_MANAGER_POLICY_ID,
  NEXT_PUBLIC_STRAVA_CLIENT_ID,
  NEXT_PUBLIC_STRAVA_CLIENT_SECRET,
  NEXT_PUBLIC_STRAVA_REDIRECT_URI,
  NEXT_PUBLIC_STRAVA_SCOPE,
  NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
} from "./EnvConsts";
import {
  STRAVA_AUTH_URL,
  STRAVA_DE_AUTHORIZE_URL,
  STRAVA_REFRESH_REQUEST_TOKEN_URL,
  STRAVA_REQUEST_TOKEN_URL,
} from "./StravaConsts";

export {
  rpcUrl,
  rpcUrlWChain,
  apiUrl,
  NEXT_PUBLIC_ALCHEMY_API_KEY,
  NEXT_PUBLIC_ALCHEMY_GAS_MANAGER_POLICY_ID,
  NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
  NEXT_PUBLIC_STRAVA_CLIENT_ID,
  NEXT_PUBLIC_STRAVA_REDIRECT_URI,
  NEXT_PUBLIC_STRAVA_SCOPE,
  NEXT_PUBLIC_STRAVA_CLIENT_SECRET,
  STRAVA_AUTH_URL,
  STRAVA_REQUEST_TOKEN_URL,
  STRAVA_REFRESH_REQUEST_TOKEN_URL,
  STRAVA_DE_AUTHORIZE_URL,
};
