const VITE_ALCHEMY_API_KEY = import.meta.env.VITE_ALCHEMY_API_KEY || "";
const VITE_ALCHEMY_GAS_MANAGER_POLICY_ID = import.meta.env.VITE_ALCHEMY_GAS_MANAGER_POLICY_ID || "";
const VITE_WALLET_CONNECT_PROJECT_ID = import.meta.env.VITE_WALLET_CONNECT_PROJECT_ID || "";
const VITE_STRAVA_CLIENT_ID = import.meta.env.VITE_STRAVA_CLIENT_ID || "";
const VITE_STRAVA_REDIRECT_URI = import.meta.env.VITE_STRAVA_REDIRECT_URI || "";
const VITE_STRAVA_SCOPE = import.meta.env.VITE_STRAVA_SCOPE || "";
const VITE_STRAVA_CLIENT_SECRET = import.meta.env.VITE_STRAVA_CLIENT_SECRET || "";
const VERCEL_PROJECT_PRODUCTION_URL = import.meta.env.VERCEL_PROJECT_PRODUCTION_URL || "";
const PORT = import.meta.env.PORT || "";
const VITE_SUBGRAPH_URI =
  import.meta.env.VITE_SUBGRAPH_URI || "http://localhost:8000/subgraphs/name/scaffold-eth/your-contract";

export {
  VITE_ALCHEMY_API_KEY,
  VITE_ALCHEMY_GAS_MANAGER_POLICY_ID,
  VITE_WALLET_CONNECT_PROJECT_ID,
  VITE_STRAVA_CLIENT_ID,
  VITE_STRAVA_REDIRECT_URI,
  VITE_STRAVA_SCOPE,
  VITE_STRAVA_CLIENT_SECRET,
  VERCEL_PROJECT_PRODUCTION_URL,
  PORT,
  VITE_SUBGRAPH_URI,
};
