import { apiUrl, rpcUrl, rpcUrlWChain } from "./AlchemyConsts";
import {
  VITE_ALCHEMY_API_KEY,
  VITE_ALCHEMY_GAS_MANAGER_POLICY_ID,
  VITE_STRAVA_CLIENT_ID,
  VITE_STRAVA_CLIENT_SECRET,
  VITE_STRAVA_REDIRECT_URI,
  VITE_STRAVA_SCOPE,
  VITE_WALLET_CONNECT_PROJECT_ID,
} from "./EnvConsts";
import {
  STRAVA_AUTH_URL,
  STRAVA_AXIOS_BASE_URL,
  STRAVA_REFRESH_REQUEST_TOKEN_URL,
  STRAVA_REQUEST_TOKEN_URL,
} from "./StravaConsts";
import { ERC_TOKEN_URL } from "./common";

export {
  rpcUrl,
  rpcUrlWChain,
  apiUrl,
  VITE_ALCHEMY_API_KEY,
  VITE_ALCHEMY_GAS_MANAGER_POLICY_ID,
  VITE_WALLET_CONNECT_PROJECT_ID,
  VITE_STRAVA_CLIENT_ID,
  VITE_STRAVA_REDIRECT_URI,
  VITE_STRAVA_SCOPE,
  VITE_STRAVA_CLIENT_SECRET,
  STRAVA_AUTH_URL,
  STRAVA_REQUEST_TOKEN_URL,
  STRAVA_REFRESH_REQUEST_TOKEN_URL,
  STRAVA_AXIOS_BASE_URL,
  ERC_TOKEN_URL,
};
