name: ChainHabits
description: ChainHabits indexer
contracts:
  - name: ChainHabits
    abi_file_path: ./abis/localhost_ChainHabits.json
    handler: ./src/EventHandlers.ts
    events:
      - event: NewUserRegistered
      - event: NewChallengeCreated
      - event: FundsWithdrawn
      - event: ChallengeCompleted
      - event: IntervalReviewCompleted
networks:
  - id: 11155111
    start_block: 6555324
    contracts:
      - name: ChainHabits 
        address: 0xd2C25Ce90d7F07b91680A009Ac7F7d9011b5Ca90